version: "3"
services:
  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - keycloak

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth
    depends_on:
      - keycloak
    volumes:
      -

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.8
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: postgrespwd
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-data:/keycloak-data
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: postgrespwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # test:
  #   image: alpine:latest
  #   entrypoint: /tmp/test/launch.sh
  #   command: "hello"
  #   environment:
  #     - name=value
  #   volumes:
  #     - C:\Users\olive\source\repos\react-ag-grid-ts\src\test:/tmp/test/

volumes:
  pgdata:
